---
title: ''
author: Forestry.io
email: support@forestry.io
description: Charity Infinity - Helps other NGOs
baseurl: ''
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
